version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - my-network

  goapp-service-a:
    container_name: goapp-a
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - zipkin
    networks:
      - my-network

  goapp-service-b:
    container_name: goapp-b
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - '8081:8180'
    depends_on:
      - zipkin
    networks:
      - my-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889" 
      - "4317:4317" 
      
networks:
  my-network:
    driver: bridge
